### ISSUE TITLE
Can not Use CLI on IBMI P7

### ISSUE THREAD

**Issue by gianluca1606** [strongloop/loopback-cli#104]
# Description/Steps to reproduce
I installed the CLI on our Ibm i P7 with the  Version V7R3. Then i tried to use the "lb" command to generate a new project and i only get messages that the command could not be found.

![image](https://user-images.githubusercontent.com/61363342/105707643-8d9fa780-5f13-11eb-8a0b-40deb6eab8c4.png)

# Expected result
The command should work just as I could use it on my ldeveloper windows machine.

# Additional information
Copy+paste the output of these two commands:
 aix ppc64 10.22.1
  
npm ls --prod --depth 0 | grep loopback results in nothing...
-

**Comment by dhmlau** [comment]
@strongloop/ibmi-maintainers, any insights?

**Comment by raymondfeng** [comment]
@gianluca1606 How did you install `loopback-cli`? `npm install -g loopback/cli`?

**Comment by gianluca1606** [comment]
> @gianluca1606 How did you install `loopback-cli`? `npm install -g loopback/cli`?

Yes I used npm install -g loopback/cli. 
I also noticed that npx is also not working, even though it is directly installed with node.js. 
Maybe I need some environment variables ?

**Comment by kadler** [comment]
You will probably need to add the node install path to your `$PATH` or configure your global install path. Because of the way we ship Node.js on IBM i, its install path is not in the default PATH and each Node.js version is installed to a different path.

The easiest way to do determine the global path is with `npm prefix -g`. You can use this to update the PATH:

```
PATH=`npm --no-update-notifier prefix -g`:$PATH
```

You can add this to your .profile or .bash_profile to have it automatically set when you log in.

Alternatively, you can also set a custom global path and hard code that in your .profile/.bash_profile. See https://docs.npmjs.com/cli/v6/using-npm/config#prefix for more details.

**Comment by gianluca1606** [comment]
> ```
> PATH=`npm --no-update-notifier prefix -g`:$PATH
> ```

I tried it but it does not help at all. 

I found this information on the profound webpage: 

`PATH=/QOpenSys/pkgs/bin:$PATH
export PATH`

[Profound Docs](https://docs.profoundlogic.com/display/PUI/Verify+Node.js+Environment+on+IBM+i)

But with the solution from profound i can only use NPX, other commands like "lb" or "nodemon" are still not usable.

**Comment by kadler** [comment]
Oops, I guess the npm prefix isn't to the bin directory, but one level up. This should do it:

```
PATH=`npm --no-update-notifier prefix -g`/bin:$PATH
```

**Comment by gianluca1606** [comment]
> Oops, I guess the npm prefix isn't to the bin directory, but one level up. This should do it:
> 
> ```
> PATH=`npm --no-update-notifier prefix -g`/bin:$PATH
> ```

Thank you, this solved the problem.

I have one more question, it is not directly related to this issue, but I do not know where I can ask these type of questions, so i hope its okay if I do it here. If not you can just close the issue or maybe move somewhere else.

Create-react-app and create-next-app have a hot reload built in out of the box. If i am not wrong the config is done with webpack.

The hot-reload does not work on the IBM I, the changes are not detected.

With nodemon I experience the same behaviour. The changes are not beeing detected.

I am missing something ?

And is there any VSCODE Extension for the remote devlopment on the IBM I or maybe an different IDE that supports it?

Thank you again.

**Comment by kadler** [comment]
We have a Node.js forum in our Ryver community where you could ask these kinds of questions. You can sign up [here](http://ibm.biz/ibmioss-chat-join) and the forum is [here](https://ibmioss.ryver.com/index.html#forums/1000127).

As far as hot-reload goes, Node.js on IBM i does not support fs.watch, since the underlying OS support is not there. I'm not sure if loopback or nodemon use chokidar (pm2 does for its hot-reload functionality), but if so you could try exporting  `CHOKIDAR_USEPOLLING=1` to work around the issue.

Regarding VS Code, there's nothing specific that I know of, though there are certainly remote dev tools like SSH/SFTP plugins and such. I'm guessing you could get more recommendations on Ryver.
