### ISSUE TITLE
Error in installation 

### ISSUE THREAD

**Issue by gauravsoni1** [strongloop/loopback-cli#57]
# Description/Steps to reproduce

Not able to install loopback-cli by using the command `sudo npm i -g loopback-cli`

# Link to reproduction sandbox

`sudo npm i -g loopback-cli`

# Expected result

Its not installing

# Additional information

Terminal is going in a installation loop, following is the error

`gyp WARN EACCES user "root" does not have permission to access the dev dir "/usr/local/lib/node_modules/loopback-cli/node_modules/ursa/.node-gyp/8.6.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/loopback-cli/node_modules/ursa/.node-gyp"
gyp verb tmpdir == cwd automatically will remove dev files after to save disk space
gyp verb command install [ '8.6.0' ]
^Cgyp verb install input version string "8.6.0"
gyp verb install installing version: 8.6.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 8.6.0
gyp verb ensuring nodedir is created /usr/local/lib/node_modules/loopback-cli/node_modules/ursa/.node-gyp/8.6.0`

System
Mac OSX - 10.13.1
Node version - 8.6.0

**Comment by raymondfeng** [comment]
If possible, please avoid using `root`. You can install isolated node versions using https://github.com/creationix/nvm and try `npm i -g loopback-cli` afterward.

**Comment by dhmlau** [comment]
@gauravsoni1 , are you still encountering this problem?  Is this issue good to close?  Thanks.

**Comment by dizid** [comment]
Same issue here.

**Comment by dhmlau** [comment]
would using `nvm` help?

**Comment by gauravsoni1** [comment]
@Diana Thanks but i am not using this anymore so not sure if its resolved.

**Comment by dhmlau** [comment]
OK @gauravsoni1.  
I'd like to keep this issue open for now, to see if using nvm could help with @dizid 's issue.  Thanks.

**Comment by dizid** [comment]
@dhmlau Issue resolved, thank you.
I am almost sure i installed nvm last week :)  (long story short)

**Comment by andreibastos** [comment]
[NPM issues](https://github.com/npm/npm/issues/17268#issuecomment-394809136)
worked for me: 
sudo npm install --unsafe-perm=true --allow-root -g loopback-cli

**Comment by paramanand-quickship** [comment]
npm: '8.7.0',
  node: '16.14.1',
  v8: '9.4.146.24-node.20',

showing this error!!!

npm i -g loopback-cli
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated uuid@3.4.0: Please upgrade to version 7 or higher. Older versions may use Math.random() in certain circumstances, which is known to be problematic. See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see request/request#3142
npm WARN deprecated loopback-boot@2.28.0: This version is no longer supported, please upgrade to 3.x
npm WARN deprecated core-js@2.6.12: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
npm ERR! code 127
npm ERR! path /root/.nvm/versions/node/v16.14.1/lib/node_modules/loopback-cli/node_modules/ejs
npm ERR! command failed
npm ERR! command sh -c node ./postinstall.js
npm ERR! sh: node: command not found

npm ERR! A complete log of this run can be found in:
npm ERR! /root/.npm/_logs/2022-04-16T13_37_29_408Z-debug-0.log





debug log :- 

0 verbose cli /root/.nvm/versions/node/v16.14.1/bin/node /root/.nvm/versions/node/v16.14.1/bin/npm
1 info using npm@8.7.0
2 info using node@v16.14.1
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:/root/.nvm/versions/node/v16.14.1/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 3ms
8 timing config:load:env Completed in 1ms
9 timing config:load:project Completed in 15ms
10 timing config:load:file:/root/.npmrc Completed in 1ms
11 timing config:load:user Completed in 2ms
12 timing config:load:file:/root/.nvm/versions/node/v16.14.1/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:validate Completed in 0ms
15 timing config:load:credentials Completed in 1ms
16 timing config:load:setEnvs Completed in 1ms
17 timing config:load Completed in 27ms
18 timing npm:load:configload Completed in 28ms
19 timing npm:load:mkdirpcache Completed in 1ms
20 timing npm:load:mkdirplogs Completed in 0ms
21 verbose title npm i loopback-cli
22 verbose argv "i" "--global" "loopback-cli"
23 timing npm:load:setTitle Completed in 2ms
24 timing config:load:flatten Completed in 3ms
25 timing npm:load:display Completed in 5ms
26 verbose logfile logs-max:10 dir:/root/.npm/_logs
27 verbose logfile /root/.npm/_logs/2022-04-16T13_47_05_735Z-debug-0.log
28 timing npm:load:logFile Completed in 5ms
29 timing npm:load:timers Completed in 1ms
30 timing npm:load:configScope Completed in 0ms
31 timing npm:load Completed in 42ms
"~/.npm/_logs/2022-04-16T13_47_05_735Z-debug-0.log" 4723L, 411202C
