### ISSUE TITLE
LB commands take forever (5-10min)

### ISSUE THREAD

**Issue by demiro** [strongloop/loopback-cli#98]
So I an trying to use lb commands like _lb model_ or _lb relation_ and it is awfully slow...

once I run it... I get the red message of Maintenance LTS mode straight away but then...
it takes from 5-10 minutes for the prompt to appear (after that responding to prompts is normal) ...

I tried to downgrade the loopback-cli to 5.0.3 but to no avail... only thing I achieved was not to see the red intro message again....

windows 10

 node -v:
v13.9.0

lb -v
5.0.3 (generator-loopback@6.2.0 loopback-workspace@5.2.1)

**Comment by dhmlau** [comment]
@demiro, sorry about the late reply. 
Have you tried to update to the latest Windows fixpack? 
There's some discussion in [this thread](https://github.com/strongloop/loopback-cli/issues/36#issuecomment-434331508) about OpenSSL.  Since I wasn't able to reproduce the problem, I wasn't able to verify whether the suggestion works. 

Other suggestions:
- v13.x is not a supported Node.js version (we support the Node.js version with even numbers, e.g. 10, 12).
- If you're just starting out on LoopBack, you might want to give LoopBack 4 a try.  Here is the getting started guide: https://loopback.io/doc/en/lb4/Getting-started.html and first tutorial: https://loopback.io/doc/en/lb4/todo-tutorial.html.
